# Generated by Django 5.0.6 on 2024-08-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_transactions_tc_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('sentiment_score', models.FloatField()),
                ('price', models.FloatField()),
                ('recommendation', models.CharField(max_length=10)),
                ('graph', models.TextField()),
                ('market_cap', models.FloatField()),
                ('current_price', models.FloatField()),
                ('volatility', models.CharField(max_length=10)),
            ],
        ),
    ]
